apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: micro-saas-dev
servers: 1
agents: 1
kubeAPI:
  hostPort: "6445"
ports:
  - port: 8081:80
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:0
